language: ruby
rvm:
- 2.3.1

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install python3-enchant

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script:
  - ./.travis-scripts/spellchecker
  - ./.travis-scripts/html-proofer

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

cache:
  bundler: true
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer # See https://github.com/gjtorikian/html-proofer/issues/381

addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors

sudo: required
